create table if not exists public.aseguramiento_semanas (
  id bigint generated by default as identity primary key,
  numero integer not null unique check (numero between 1 and 52),
  activo boolean not null default true
);

create table if not exists public.aseguramiento_productos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.aseguramiento_proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.aseguramiento_presentaciones (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.aseguramiento_colores (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.aseguramiento_formulas_c (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.aseguramiento_categorias_toxicologicas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

alter table public.aseguramiento_plaguicidas
  add column if not exists formula_c text,
  add column if not exists cat_toxic text,
  add column if not exists nombre_quien_asegura text,
  add column if not exists nombre_autoriza text;

create table if not exists public.mipe_tipos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.mipe_direcciones (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists public.mipe_grupos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

insert into public.aseguramiento_semanas (numero)
select generate_series(1, 52)
on conflict (numero) do nothing;

insert into public.aseguramiento_presentaciones (nombre)
values
  ('1 L'),
  ('500 ML'),
  ('250 ML'),
  ('100 ML'),
  ('1 KG'),
  ('500 G'),
  ('250 G'),
  ('SACO'),
  ('BOLSA'),
  ('CAJA'),
  ('AEROSOL'),
  ('OTRO')
on conflict (nombre) do nothing;

insert into public.aseguramiento_colores (nombre)
values
  ('AMARILLO'),
  ('AZUL'),
  ('BLANCO'),
  ('CAFE'),
  ('INCOLORO'),
  ('NARANJA'),
  ('ROJO'),
  ('VERDE'),
  ('OTRO'),
  ('NO DEFINIDO')
on conflict (nombre) do nothing;

insert into public.aseguramiento_formulas_c (nombre)
values ('SI'), ('NO')
on conflict (nombre) do nothing;

insert into public.aseguramiento_categorias_toxicologicas (nombre)
values ('IA'), ('IB'), ('II'), ('III'), ('IV')
on conflict (nombre) do nothing;

insert into public.mipe_tipos (nombre)
values ('ASPERSION'), ('APLICACION DIRIGIDA'), ('NEBULIZACION'), ('OTRO')
on conflict (nombre) do nothing;

insert into public.mipe_direcciones (nombre)
values ('NORTE'), ('SUR'), ('ORIENTE'), ('OCCIDENTE'), ('CENTRO')
on conflict (nombre) do nothing;

insert into public.mipe_grupos (nombre)
values ('GRUPO 1'), ('GRUPO 2'), ('GRUPO 3'), ('GRUPO 4'), ('GRUPO 5'), ('GRUPO 6'), ('GRUPO 7')
on conflict (nombre) do nothing;

grant select on public.aseguramiento_semanas to anon, authenticated;
grant select on public.aseguramiento_productos to anon, authenticated;
grant select on public.aseguramiento_proveedores to anon, authenticated;
grant select on public.aseguramiento_presentaciones to anon, authenticated;
grant select on public.aseguramiento_colores to anon, authenticated;
grant select on public.aseguramiento_formulas_c to anon, authenticated;
grant select on public.aseguramiento_categorias_toxicologicas to anon, authenticated;
grant select on public.mipe_tipos to anon, authenticated;
grant select on public.mipe_direcciones to anon, authenticated;
grant select on public.mipe_grupos to anon, authenticated;

alter table public.aseguramiento_semanas enable row level security;
alter table public.aseguramiento_productos enable row level security;
alter table public.aseguramiento_proveedores enable row level security;
alter table public.aseguramiento_presentaciones enable row level security;
alter table public.aseguramiento_colores enable row level security;
alter table public.aseguramiento_formulas_c enable row level security;
alter table public.aseguramiento_categorias_toxicologicas enable row level security;
alter table public.mipe_tipos enable row level security;
alter table public.mipe_direcciones enable row level security;
alter table public.mipe_grupos enable row level security;

drop policy if exists "Catalogo semanas visible" on public.aseguramiento_semanas;
create policy "Catalogo semanas visible"
on public.aseguramiento_semanas for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo productos visible" on public.aseguramiento_productos;
create policy "Catalogo productos visible"
on public.aseguramiento_productos for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo proveedores visible" on public.aseguramiento_proveedores;
create policy "Catalogo proveedores visible"
on public.aseguramiento_proveedores for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo presentaciones visible" on public.aseguramiento_presentaciones;
create policy "Catalogo presentaciones visible"
on public.aseguramiento_presentaciones for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo colores visible" on public.aseguramiento_colores;
create policy "Catalogo colores visible"
on public.aseguramiento_colores for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo formulas C visible" on public.aseguramiento_formulas_c;
create policy "Catalogo formulas C visible"
on public.aseguramiento_formulas_c for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo categorias toxicologicas visible" on public.aseguramiento_categorias_toxicologicas;
create policy "Catalogo categorias toxicologicas visible"
on public.aseguramiento_categorias_toxicologicas for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo tipos MIPE visible" on public.mipe_tipos;
create policy "Catalogo tipos MIPE visible"
on public.mipe_tipos for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo direcciones MIPE visible" on public.mipe_direcciones;
create policy "Catalogo direcciones MIPE visible"
on public.mipe_direcciones for select
to anon, authenticated
using (activo = true);

drop policy if exists "Catalogo grupos MIPE visible" on public.mipe_grupos;
create policy "Catalogo grupos MIPE visible"
on public.mipe_grupos for select
to anon, authenticated
using (activo = true);
