class FormularioLayoutService {
  static const String mipe = 'mipe';
  static const String almacen = 'almacen';

  static const Map<String, List<String>> ordenesPredeterminados = {
    mipe: [
      'bloque',
      'bombero',
      'jefe_mipe',
      'semana',
      'dia',
      'temperatura',
      'humedad',
      'tipo',
      'direccion',
      'productos',
      'volumen_cama',
      'numero_camas',
      'grupos_fumigadores',
      'equipo',
      'ire',
      'administrador_autoriza',
      'firma_registra',
      'firma_autoriza',
    ],
    almacen: [
      'semana',
      'nombre_producto',
      'casa_comercial',
      'total_unidades',
      'presentacion',
      'cantidad',
      'lote',
      'formula_c',
      'categoria_toxicologica',
      'fecha_vencimiento',
      'estado_etiqueta',
      'estado_tapa',
      'sellos',
      'puntos_extraccion',
      'cumplimiento',
      'color',
      'otro_color',
      'ph',
      'densidad',
      'observaciones',
      'administrador_autoriza',
      'firma_asegura',
      'firma_autoriza',
    ],
  };

  static const Map<String, List<List<String>>> filasPredeterminadas = {
    mipe: [
      ['bloque', 'bombero'],
      ['jefe_mipe'],
      ['semana'],
      ['dia'],
      ['temperatura', 'humedad'],
      ['tipo', 'direccion'],
      ['productos'],
      ['volumen_cama', 'numero_camas'],
      ['grupos_fumigadores'],
      ['equipo'],
      ['ire'],
      ['administrador_autoriza'],
      ['firma_registra', 'firma_autoriza'],
    ],
    almacen: [
      ['semana', 'nombre_producto'],
      ['casa_comercial'],
      ['total_unidades', 'presentacion'],
      ['cantidad', 'lote'],
      ['formula_c', 'categoria_toxicologica'],
      ['fecha_vencimiento'],
      ['estado_etiqueta'],
      ['estado_tapa'],
      ['sellos'],
      ['puntos_extraccion'],
      ['cumplimiento'],
      ['color'],
      ['otro_color'],
      ['ph', 'densidad'],
      ['observaciones'],
      ['administrador_autoriza'],
      ['firma_asegura', 'firma_autoriza'],
    ],
  };

  static const Map<String, String> nombresFormularios = {
    mipe: 'Registro MIPE',
    almacen: 'Aseguramiento de almacén',
  };

  static const Map<String, List<String>> camposRepetibles = {
    mipe: [
      'producto_item_nombre',
      'producto_item_dosis',
      'producto_item_categoria',
      'producto_item_blanco',
    ],
    almacen: [],
  };

  static const Map<String, Map<String, String>> nombresBloques = {
    mipe: {
      'bloque': 'Bloque',
      'bombero': 'Bombero',
      'jefe_mipe': 'Jefe MIPE',
      'semana': 'Semana',
      'dia': 'Día de aplicación',
      'temperatura': 'Temperatura',
      'humedad': 'Humedad relativa',
      'tipo': 'Tipo de aplicación',
      'direccion': 'Dirección',
      'productos': 'Productos',
      'producto_item_nombre': 'Nombre del Producto',
      'producto_item_dosis': 'Dosis',
      'producto_item_categoria': 'Cat. Tóxico',
      'producto_item_blanco': 'Blanco Biológico',
      'volumen_cama': 'Volumen de cama',
      'numero_camas': 'Número de camas',
      'grupos_fumigadores': 'Grupo fumigador',
      'equipo': 'Equipo',
      'ire': 'Horas de reingreso (I.R.E.)',
      'administrador_autoriza': 'Administrador que autoriza',
      'firma_registra': 'Firma de quien registra',
      'firma_autoriza': 'Firma del administrador',
    },
    almacen: {
      'semana': 'Semana',
      'nombre_producto': 'Nombre del producto',
      'casa_comercial': 'Casa comercial',
      'presentacion': 'Presentación',
      'total_unidades': 'Cantidad de unidades',
      'lote': 'Lote',
      'cantidad': 'Cantidad (cc/g)',
      'formula_c': 'Fórmula C',
      'categoria_toxicologica': 'Categoría toxicológica',
      'fecha_vencimiento': 'Fecha de vencimiento',
      'estado_etiqueta': 'Estado de etiqueta',
      'estado_tapa': 'Estado de tapa',
      'sellos': 'Sellos',
      'puntos_extraccion': 'Puntos de extracción',
      'cumplimiento': 'Cumplimiento',
      'color': 'Color',
      'otro_color': 'Especificar otro color',
      'ph': 'pH',
      'densidad': 'Densidad',
      'observaciones': 'Observaciones',
      'administrador_autoriza': 'Administrador que autoriza',
      'firma_asegura': 'Firma de Asegura',
      'firma_autoriza': 'Firma de Autoriza',
    },
  };
}
